version : "3.7"
services:
  postgres:
    image: "maximize/postgres"
    ports:
      - "5432:5432"
    dns_search: "."
    volumes:
      - db-volume:/var/lib/postgresql/data:rw

  discoverysrvc:
    image: "maximize/discoverysrvc"
    environment:
      - spring.profiles.active=native
      - eureka.instance.hostName=discoverysrvc
      - eureka.instance.preferIpAddress=false
    ports:
      - "8761:8761"
    dns_search: "."

  configsrvc:
    image: "maximize/configsrvc"
    environment:
      - eureka.client.service-url.defaultZone=http://discoverysrvc:8761/eureka
    ports:
      - "8888:8888"
    dns_search: "."

  usersrvc:
    image: "maximize/usersrvc"
    depends_on:
      - configsrvc
      - postgres
      - activemq
    ports:
      - "8089:8089"
    dns_search: "."
    environment:
      - spring.cloud.config.uri=http://configsrvc:8888/
      - eureka.client.service-url.defaultZone=http://discoverysrvc:8761/eureka

  activemq:
    image: webcenter/activemq 
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    environment:
    - ACTIVEMQ_MIN_MEMORY=512
    - ACTIVEMQ_MAX_MEMORY=2048
    volumes:
    - ./tmp/volumes/log/activemq:/var/log/activemq

volumes:
  db-volume:
