version : "3.7"
services:
  postgres:
    image: "maximize/postgres"
    ports:
      - "5432:5432"
    dns_search: "."
    volumes:
      - db-volume:/var/lib/postgresql/data:rw

  discovery-service:
    image: "maximize/discovery-service"
    environment:
      - spring.profiles.active=native
      - eureka.instance.hostName=discovery-service
      - eureka.instance.preferIpAddress=false
    ports:
      - "8761:8761"
    dns_search: "."

  config-service:
    image: "maximize/config-service"
    depends_on:
      - discovery-service 
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
    ports:
      - "8888:8888"
    dns_search: "."

  user-service:
    image: "maximize/user-service"
    depends_on:
      - discovery-service 
      - config-service
      - postgres
      - activemq
    ports:
      - "8089:8089"
    dns_search: "."
    environment:
      - spring.cloud.config.uri=http://config-service:8888/
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka

  activemq:
    image: webcenter/activemq 
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    environment:
    - ACTIVEMQ_MIN_MEMORY=512
    - ACTIVEMQ_MAX_MEMORY=2048
    volumes:
    - ./tmp/volumes/log/activemq:/var/log/activemq

volumes:
  db-volume:
