version : "3.7"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    dns_search: "."
    volumes:
      - db-volume:/var/lib/postgresql/data:rw

  configsrvc:
    image: "maximize/configsrvc"
    environment:
      - spring.profiles.active=native
      - spring.cloud.config.server.native.searchLocations=file:/tmp/max/config
    volumes:
      # This exits so we can mount this folder in the container & not use github
      - /home/bgants/projects/maximize-configs:/tmp/max/config
    ports:
      - "8888:8888"
    dns_search: "."

  usersrvc:
    image: "maximize/usersrvc"
    depends_on:
      - configsrvc
      - postgres
    ports:
      - "8089:8089"
    dns_search: "."
    environment:
      - spring.profiles.active=native
      - spring.cloud.config.uri=http://configsrvc:8888

  activemq:
    image: webcenter/activemq 
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    environment:
    - ACTIVEMQ_MIN_MEMORY=512
    - ACTIVEMQ_MAX_MEMORY=2048
    volumes:
    - ./tmp/volumes/log/activemq:/var/log/activemq

volumes:
  db-volume:

