server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
       git:
         uri: https://github.com/bgants/maximize-configs
         force-pull: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: ALWAYS